Repository elk-zone/elk, pull requests merged in 2023-03, with the labels that each got.

#1701 fix: extended docker-compose.yml to addres Bug #1696
  README.md
  docker-compose.yaml
Labels: c: infra

#319 feat: basic keyboard shortcuts
  components/magickeys/MagickeysKeyboardShortcuts.vue
  components/modal/ModalContainer.vue
  components/publish/PublishWidget.vue
  components/status/StatusCard.vue
  components/status/StatusDetails.vue
  composables/dialog.ts
  composables/magickeys.ts
  locales/en.json
  plugins/1.scroll-to-top.ts
  plugins/magic-keys.client.ts
  styles/vars.css
Labels: c: feature

#1513 fix: sticky hover style on mobile
  components/account/AccountFollowButton.vue
  components/account/AccountMoreButton.vue
  components/nav/NavSideItem.vue
  components/status/StatusActionButton.vue
  components/status/StatusActions.vue
  components/status/StatusActionsMore.vue
  components/tag/TagActionButton.vue
  unocss.config.ts
Labels: c: feature

#1884 feat(i18n): `es` base sync
  locales/es.json
Labels: c: i18n
