Repository elk-zone/elk, pull requests merged in 2023-01, with the labels that each got.

#1006 perf: mock semver import
  mocks/semver.ts
  nuxt.config.ts
Labels: c: performance

#1061 fix: adjust background of account name when it's a link
  components/account/AccountInlineInfo.vue
Labels: c: ui

#1102 feat: support additional html elements
  composables/content-parse.ts
  styles/global.css
  tests/__snapshots__/content-rich.test.ts.snap
  tests/content-rich.test.ts
Labels: c: feature

#1065 fix: hide actions panel in status detail when use zen mode
  components/status/StatusDetails.vue
Labels: c: ui, s: needs decision

#1139 fix: use user id in cache key
  composables/cache.ts
Labels: c: bug, p: 2-high

#1144 feat: implement social previews by redirecting to origin server
  plugins/social.server.ts
Labels: c: feature, p: 1-normal

#1174 fix: catch more bots with redirects
  plugins/social.server.ts
Labels: c: bug

#1175 fix: disallow all indexing on canary site and indexing of auth-only pages in prod
  public-staging/robots.txt
  public/robots.txt
Labels: c: bug

#1186 test: add `vitest-environment-nuxt`
  composables/idb/index.ts
  composables/masto/statusDrafts.ts
  composables/users.ts
  nuxt.config.ts
  package.json
  pages/[[server]]/@[account]/[status].vue
  pnpm-lock.yaml
  shims.d.ts
  tests/content-rich.test.ts
  tests/html-parse.test.ts
  tests/html-to-text.test.ts
  tests/language.test.ts
  tests/reorder-timeline.test.ts
  vitest.config.mjs
  vitest.config.ts
Labels: c: chore

#1188 feat(i18n): de-DE update locale
  locales/de-DE.json
Labels: c: i18n

#1191 fix: initialise stream promise before stream is available
  composables/masto/notification.ts
Labels: c: bug

#1201 perf: improve perf on rendering long list of replies
  pages/[[server]]/@[account]/[status].vue
  pages/[[server]]/@[account]/index.vue
  pages/[[server]]/tags/[tag].vue
Labels: c: bug, c: performance

#1198 fix: publish widget mentions
  components/content/ContentMentionGroup.vue
  components/publish/PublishWidget.vue
  composables/masto/account.ts
Labels: c: bug, p: 2-high

#1146 fix: fall back to votes count if voters count is not supplied
  components/status/StatusPoll.vue
Labels: c: bug

#1052 feat: add docker support
  .dockerignore
  Dockerfile
Labels: s: needs decision

#1390 fix: tag link
  components/tag/TagCard.vue
Labels: c: bug

#1376 feat: range of font size
  components/settings/SettingsFontSize.vue
  composables/settings/definition.ts
  composables/settings/storage.ts
  constants/index.ts
  constants/options.ts
  locales/ar-EG.json
  locales/de-DE.json
  locales/en-US.json
  locales/es-ES.json
  locales/fr-FR.json
  locales/id-ID.json
  locales/ja-JP.json
  locales/pt-PT.json
  locales/tr-TR.json
  locales/uk-UA.json
  locales/zh-CN.json
  locales/zh-TW.json
  plugins/setup-global-effects.client.ts
  plugins/setup-head-script.server.ts
  unocss.config.ts
Labels: p: 2-high

#1391 feat: follow tags from trends page
  components/tag/TagActionButton.vue
  components/tag/TagCard.vue
Labels: c: feature

#1432 fix: tag if condition
  components/tag/TagActionButton.vue
Labels: c: bug

#1516 perf!: allow tree-shaking unstorage drivers
  modules/tauri/index.ts
  modules/tauri/runtime/storage-config.ts
  nuxt.config.ts
  server/shared.ts
Labels: c: performance

#1497 chore: update zh-cn locales
  locales/zh-CN.json
Labels: i18n: zh-cn

#1434 fix: French translation revision
  locales/fr-FR.json
Labels: i18n: fr
