Repository elk-zone/elk, pull requests merged in 2023-02, with the labels that each got.

#1571 feat(i18n): sync zh-CN
  locales/zh-CN.json
Labels: c: i18n

#1596 fix: lists link on side nav
  components/nav/NavSide.vue
Labels: p: 2-high

#1608 fix: hide side nav in zen mode
  layouts/default.vue
Labels: p: 2-high

#1620 feat: image pinch to zoom
  components/modal/ModalMediaPreviewCarousel.vue
Labels: c: feature, c: ui

#1647 perf: tree-shake dependencies from server
  components/common/CommonInputImage.vue
  components/modal/ModalMediaPreviewCarousel.vue
  components/tiptap/TiptapEmojiList.vue
  composables/masto/publish.ts
  composables/tiptap.ts
  composables/tiptap/suggestion.ts
  composables/users.ts
  mocks/class.ts
  mocks/prosemirror.ts
  mocks/tiptap.ts
  nuxt.config.ts
  pages/settings/users/index.vue
Labels: c: performance

#1650 fix: work around hotfix cloudflare kv storage bug
  server/cloudflare-driver.ts
  server/shared.ts
Labels: c: bug

#1665 feat: allow using elk as a nuxt layer
  modules/pwa/i18n.ts
  modules/stale-dep.ts
  package.json
  pnpm-lock.yaml
Labels: c: chore

#1675 refactor: use server auto-imports
  modules/tauri/index.ts
  server/api/[server]/clear.ts
  server/api/[server]/login.ts
  server/api/[server]/oauth.ts
  server/api/list-servers.ts
  server/utils/shared.ts
Labels: c: chore

#1722 fix: add badge to bottom bar notifications icon
  components/nav/NavBottom.vue
Labels: c: ui

#1575 fix(i18n): update de-DE locale
  locales/de-DE.json
Labels: c: i18n

#1229 fix(i18n): Update nl-NL.json
  locales/nl-NL.json
Labels: c: i18n

#1672 feat: copy content warning when replying
  composables/masto/statusDrafts.ts
Labels: c: bug

#1820 feat(i18n): include missing Polish translations
  locales/pl-PL.json
Labels: c: i18n
