Repository elk-zone/elk, pull requests merged in 2023-04, with the labels that each got.

#1865 feat(i18n): sync zh-CN with en
  locales/zh-CN.json
Labels: c: i18n

#1981 fix: use `purpose: any` for normal pwa icon
  modules/pwa/i18n.ts
Labels: c: bug

#1745 fix: Re-enable user card hover over mentions in posts
  composables/misc.ts
Labels: c: feature

#1733 feat(editor): Respect default privacy setting of the account (2nd)
  components/publish/PublishWidget.vue
  components/publish/PublishWidgetFull.client.vue
  composables/masto/statusDrafts.ts
Labels: c: feature

#1817 fix(default): update layout to use dynamic vh
  layouts/default.vue
  unocss.config.ts
Labels: c: ui
