Repository elk-zone/elk, pull requests merged in 2023-05, with the labels that each got.

#1966 chore(deps): replace esno with tsx
  package.json
  pnpm-lock.yaml
Labels: c: dependencies

#2060 feat(i18n): Update fr-FR locale
  locales/fr-FR.json
Labels: c: i18n, i18n: fr

#2054 fix(i18n): Updated nl-NL.json
  locales/nl-NL.json
Labels: c: i18n

#2067 feat: add 'use star favorite icon' preference
  components/account/AccountMoreButton.vue
  components/nav/NavSide.vue
  components/status/StatusActions.vue
  components/status/StatusActionsMore.vue
  composables/settings/definition.ts
  locales/en.json
  locales/ja-JP.json
  pages/favourites.vue
  pages/settings/preferences/index.vue
Labels: c: feature

#2120 fix: handle hidden followers/following count
  components/account/AccountPostsFollowers.vue
Labels: p: 1-normal, c: fediverse
